### ISSUE TITLE
Introduce Spring Security

### ISSUE THREAD

**Issue by molgergo01** [molgergo01/BBG-Pictures-Repository-Backend#25]
Encrypt passwords when persisting to db
Refactors member endpoints to use JdbcUserDetailsManager
Add Basicauth

**Comment by molgergo01** [comment]
Pull request: https://github.com/molgergo01/BBG-Pictures-Repository-Backend/pull/26

**Comment by SabianRobi** [comment]
Completed in: b4bba9618a00ce6eca6520caec0ace6bee3abfc1
