### ISSUE TITLE
Implement Member Read endpoint

### ISSUE THREAD

**Issue by molgergo01** [molgergo01/BBG-Pictures-Repository-Backend#3]

**Comment by molgergo01** [comment]
Completed in: https://github.com/molgergo01/BBG-Pictures-Repository-Backend/commit/cfbbd46d21c2ebe80697efb2b08892312d25a525

**Comment by SabianRobi** [comment]
I can see the endpoint for getting all the members, but not an endpoint to get a single member - only patch and delete for that.

**Comment by molgergo01** [comment]
Added single member get endpoint in: 0e0c02b28235292927065e38893f531989c19744
